//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNetData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public Comment()
        {
            this.CreationDate = DateTime.Now;
            this.ModificationDate = DateTime.Now;
        }
        public Comment(string text, User user, Film film) {
            this.Text = text;
            this.CreationDate = DateTime.Now;
            this.ModificationDate = DateTime.Now;
            this.User = user;
            this.Film = film;
        }

        public int Id { get; set; }
        public Nullable<double> Score { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Film Film { get; set; }
    }
}
