//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNetData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Film  
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Comment = new HashSet<Comment>();
        }

        public Film(string title, string genres, string synopsis, string director) {
            this.Titre = title;
            this.Genres = genres;
            this.Synopsis = synopsis;
            this.Director = director;
            this.Comment = new HashSet<Comment>();
            }
    
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Genres { get; set; }
        public string Synopsis { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<short> Year { get; set; }
        public string Director { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
